# For more information: https://laravel.com/docs/sail
version: '3'
services:
    ngrok:
        image: wernight/ngrok:latest
        ports:
        - 4040:4040
        environment:
            NGROK_PROTOCOL: http
            NGROK_PORT: 80
        networks: 
            - sail
        depends_on:
            - laravel.test 
    laravel.test: &laravel_test
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - "127.0.0.1:$DDEV_HOST_WEBSERVER_PORT:8000"
            - '${APP_PORT:-80}:80'
            - 6001:6001  #websocket
        entrypoint: ['sh', '-c', 'start-container  & php artisan queue:work']
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        healthcheck:
            test: "${DOCKER_HEALTHCHECK_TEST:-curl -f http://localhost/ || exit 1}"
            interval: "60s"
            timeout: "3s"
            start_period: "5s"
            retries: 3                    
        depends_on:
            - mysql
            - redis        
    selenium:
        image: 'selenium/standalone-chrome'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail
        depends_on:
            - laravel.test
        ports:
            - 4444:4444
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
    # memcached:
    #     image: 'memcached:alpine'
    #     ports:
    #         - '11211:11211'
    #     networks:
    #         - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
