export enum UserStoreActions {
  INIT_CHANNEL_LISTENERS = 'INIT_CHANNEL_LISTENERS',
  INIT_PUBLIC_NOTIFIABLE_CHANNEL_LISTENER = 'INIT_PUBLIC_NOTIFIABLE_CHANNEL_LISTENER',
}

export default UserStoreActions